{
  lib,
  stdenv,
  fetchurl,
  autoreconfHook,
  bison,
  flex,
  cmake,
  pkg-config,
  perl,
  python3,
  texinfo,
  ghostscript,

  # build inputs
  eigen,
  boehmgc,
  ncurses,
  readline,
  zlib,
  curl,
  boost,
  fftw,
  libtirpc,

  # optional deps — null when not available
  gsl ? null,
  glm ? null,
  libsigsegv ? null,
  imagemagick ? null,
  libGL ? null,
  libGLU ? null,
  libglut ? null,
  libglvnd ? null,

  # texlive integration
  texliveSmall ? null,
}:

stdenv.mkDerivation (finalAttrs: {
  version = "3.10";
  pname = "asymptote";

  outputs = [
    "out"
    "man"
    "info"
    "doc"
    "tex"
  ];

  src = fetchurl {
    url = "mirror://sourceforge/asymptote/${finalAttrs.version}/asymptote-${finalAttrs.version}.src.tgz";
    hash = "sha256-0nvo/vJQ1dwzhgK/cj4dCejNHoXBmatMgHQwif2M0sc=";
  };

  # override with TeX Live containers to avoid building sty, docs from source
  texContainer = null;
  texdocContainer = null;

  nativeBuildInputs = [
    autoreconfHook
    bison
    flex
    texinfo
    cmake
    perl
    python3
    pkg-config
    ghostscript
  ]
  ++ lib.optional (finalAttrs.texContainer == null || finalAttrs.texdocContainer == null) (
    if texliveSmall != null then
      texliveSmall.withPackages (
        ps: with ps; [
          epsf
          cm-super
          ps.texinfo
          media9
          ocgx2
          collection-latexextra
        ]
      )
    else
      throw "asymptote: texliveSmall is required to build from source"
  );

  buildInputs = [
    eigen
    boehmgc
    ncurses
    readline
    zlib
    curl
    fftw
    gsl
    libsigsegv
    imagemagick
    boost
  ]
  ++ lib.optionals stdenv.hostPlatform.isLinux [ libtirpc ];

  propagatedBuildInputs = [
    glm
  ]
  ++ lib.optionals stdenv.hostPlatform.isLinux [
    libglut
    libGLU
    libGL
    libglvnd
  ];

  # do not build $tex/ls-R which will be generated by texlive.withPackages
  # do not build and install sty and docs, if provided by tex/texdoc texlive containers
  preConfigure = ''
    HOME=$TMP
    substituteInPlace Makefile.in \
      --replace-fail ' install-texhash' '''
    if [[ -n $texContainer ]] ; then
      sed -i Makefile.in -e '/(\(latex\|context\)dir)/d'
      substituteInPlace Makefile.in \
        --replace-fail 'asy sty' 'asy'
    else
      prependToVar configureFlags "--with-latex=$tex/tex/latex" "--with-context=$tex/tex/context/third"
    fi
    if [[ -n $texdocContainer ]] ; then
      substituteInPlace Makefile.in \
        --replace-fail ' install-man' ''' \
        --replace-fail 'docdir = $(DESTDIR)@docdir@' 'docdir = $(TMP)/doc'
    fi
  '';

  configureFlags = [
    "--enable-gc=system"
    # Disable features that require missing dependencies
    "--disable-gl"
    "--disable-gsl"
  ];

  env.NIX_CFLAGS_COMPILE = "-I${boehmgc.dev}/include/gc";

  postInstall = ''
    # Remove xasy (Qt5 GUI) since we don't have Qt5
    rm -f "$out"/bin/xasy

    if [[ -z $texdocContainer ]] ; then
      mv "$info"/share/info/asymptote/*.info "$info"/share/info/
      sed -i -e 's|(asymptote/asymptote)|(asymptote)|' "$info"/share/info/asymptote.info
      rmdir "$info"/share/info/asymptote
      rm -f "$info"/share/info/dir
    fi
    install -Dt $out/share/emacs/site-lisp/${finalAttrs.pname} $out/share/asymptote/*.el
  '';

  # fixupPhase crashes if the outputs are not directories
  preFixup = ''
    if [[ -n $texContainer ]] ; then
      mkdir -p "$tex"
    fi
    if [[ -n $texdocContainer ]] ; then
      mkdir -p "$doc" "$man" "$info"
    fi
  '';

  postFixup = ''
    if [[ -n $texContainer ]] ; then
      rmdir "$tex"
      ln -s "$texContainer" "$tex"
    fi
    if [[ -n $texdocContainer ]] ; then
      mkdir -p "$man/share" "$info/share"
      ln -s "$texdocContainer" "$doc/share"
      ln -s "$texdocContainer/doc/man" "$man/share"
      ln -s "$texdocContainer/doc/info" "$info/share"
    fi
  '';

  dontUseCmakeConfigure = true;

  enableParallelBuilding = true;
  enableParallelInstalling = false;

  meta = {
    description = "Tool for programming graphics intended to replace Metapost";
    homepage = "https://asymptote.sourceforge.io/";
    license = lib.licenses.gpl3Plus;
    platforms = lib.platforms.linux ++ lib.platforms.darwin;
  };
})
