{
  stdenv,
  lib,
  fetchFromGitHub,
  brotli,
  cmake,
  giflib,
  gtest,
  libjpeg,
  libpng,
  libwebp,
  gdk-pixbuf,
  pkg-config,
  makeWrapper,
  zlib,
  asciidoc,
  graphviz,
  doxygen,
  python3,
  lcms2,
  enablePlugins ? true,
}:

let
  loadersPath = "${gdk-pixbuf.binaryDir}/jxl-loaders.cache";
in

stdenv.mkDerivation rec {
  pname = "libjxl";
  version = "0.12.0";

  outputs = [
    "out"
    "bin"
    "dev"
    "benchmark"
  ];

  src = fetchFromGitHub {
    owner = "libjxl";
    repo = "libjxl";
    tag = "v${version}";
    hash = "sha256-rJyvJo1ZveE1pvMErK9ilFQA0NXkD2ka93L+1gXeqf8=";
    # There are various submodules in `third_party/`.
    fetchSubmodules = true;
  };

  nativeBuildInputs = [
    cmake
    cmake.configurePhaseHook
    pkg-config
    gdk-pixbuf
    makeWrapper
    asciidoc
    doxygen
    python3
  ];

  depsBuildBuild = [
    graphviz
  ];

  buildInputs = [
    lcms2
    giflib
    gtest
    libjpeg
    libpng
    libwebp
    gdk-pixbuf
    zlib
  ];

  propagatedBuildInputs = [
    brotli
  ];

  cmakeFlags = [
    # Fix broken .pc file paths for vendored highway
    "-DCMAKE_INSTALL_LIBDIR=lib"
    "-DCMAKE_INSTALL_INCLUDEDIR=include"

    # For C dependencies like brotli, which are dynamically linked,
    # we want to use the system libraries, so that we don't have to care about
    # installing their .so files generated by this build.
    # The other C++ dependencies are statically linked in, so there
    # using the vendorered ones is easier.
    "-DJPEGXL_FORCE_SYSTEM_BROTLI=ON"

    # Use our version of gtest
    "-DJPEGXL_FORCE_SYSTEM_GTEST=ON"

    "-DJPEGXL_ENABLE_SKCMS=OFF"
    "-DJPEGXL_FORCE_SYSTEM_LCMS2=ON"

    # libhwy/highway not available as system library yet
    "-DJPEGXL_FORCE_SYSTEM_HWY=OFF"

    # openexr not available
    "-DJPEGXL_ENABLE_OPENEXR=OFF"

    # gperftools not available
    "-DJPEGXL_ENABLE_TCMALLOC=OFF"
  ]
  ++ lib.optionals enablePlugins [
    # Enable plugins, such as:
    # * the `gdk-pixbuf` one, which allows applications like `eog` to load jpeg-xl files
    "-DJPEGXL_ENABLE_PLUGINS=ON"
  ]
  ++ lib.optionals stdenv.hostPlatform.isStatic [
    "-DJPEGXL_STATIC=ON"
  ]
  ++ lib.optionals stdenv.hostPlatform.isAarch32 [
    "-DJPEGXL_FORCE_NEON=ON"
  ];

  # the second substitution fix regex for a2x script
  # https://github.com/libjxl/libjxl/pull/3842
  postPatch = ''
    # Remove vendored copies of dependencies we use from the system
    # Keep highway (third_party/highway) since libhwy is not yet available
    rm -rf third_party/brotli/
    rm -rf third_party/googletest/
    rm -rf third_party/lcms/

    substituteInPlace plugins/gdk-pixbuf/jxl.thumbnailer \
      --replace '/usr/bin/gdk-pixbuf-thumbnailer' "$out/libexec/gdk-pixbuf-thumbnailer-jxl"
    substituteInPlace CMakeLists.txt \
      --replace 'sh$' 'sh( -e$|$)'
  '';

  # Move `benchmark_xl` into a separate output to avoid a file collision
  # with the `benchmark_xl` binary provided by `jpegli`.
  postInstall = ''
    moveToOutput "bin/benchmark_xl" "$benchmark"
  ''
  + lib.optionalString enablePlugins ''
    GDK_PIXBUF_MODULEDIR="$out/${gdk-pixbuf.moduleDir}" \
    GDK_PIXBUF_MODULE_FILE="$out/${loadersPath}" \
      gdk-pixbuf-query-loaders --update-cache
  ''
  # Cross-compiled gdk-pixbuf doesn't support thumbnailers
  + lib.optionalString (enablePlugins && stdenv.hostPlatform == stdenv.buildPlatform) ''
    mkdir -p "$out/bin"
    makeWrapper ${gdk-pixbuf}/bin/gdk-pixbuf-thumbnailer "$out/libexec/gdk-pixbuf-thumbnailer-jxl" \
      --set GDK_PIXBUF_MODULE_FILE "$out/${loadersPath}"
  '';

  env = lib.optionalAttrs stdenv.hostPlatform.isAarch32 {
    CXXFLAGS = "-mfp16-format=ieee";
  };

  meta = {
    homepage = "https://github.com/libjxl/libjxl";
    description = "JPEG XL image format reference implementation";
    license = lib.licenses.bsd3;
    platforms = lib.platforms.all;
    identifiers.cpeParts = {
      vendor = "libjxl_project";
      product = "libjxl";
    };
  };
}
